---
# tasks file for roles/sys_utils_manager
- name: update cash
  apt:
    update_cache: yes


- name: install atop
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - atop
    - htop
    - nmap
    - tcpdump
    - mtr
    - strace
  tags: inst_all


- name: install atop
  apt:
    name: atop
  tags: atop