---
# handlers file for node_exporter

- name: Restart node_exporter
  systemd:
    name: node_exporter
    state: restarted
    enabled: yes

- name: Daemon-reload
  systemd:
    daemon_reload: yes

