---
# tasks file for python_app_setup
- name: Install deps
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - python3-venv
    - python3-pip

- name: Check if app folder exists
  file:
    path: "{{ prj_dir }}"
    state: directory

- name: copy app.py
  copy:
    src: app.py
    dest: "{{ prj_dir }}"


- name: Create venv
  command: python3 -m venv "{{ venv_dir }}"
  args:
    creates: "{{ venv_dir }}"

- name: Install requiments (flask)
  pip:
    name: flask
    virtualenv: "{{ venv_dir }}"

- name: Create service
  template:
    src: myapp.service.j2
    dest: /etc/systemd/system/myapp.service

- name: Reload systemd
  systemd_service:
    daemon_reload: true

- name: Start myapp
  systemd_service:
    name: myapp.service
    state: started